name: Build

env:
  # The name of the main module repository
  main_project_module: app

  # The name of the Play Store
  playstore_name: WearBili

  # Keystore Path
  ks_path: keystore.jks

  # Keystore Password
  ks_store_pass: bakanotbaka

  # Keystore Alias
  ks_alias: bakanotbaka

  # Keystore Alias Password
  ks_alias_pass: bakanotbaka

on:

  push:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2

      - name: Setup git submodule
        run: |
          git submodule init
          git submodule update --remote
          ls libs/Bilibili-Kotlin-SDK 

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Create APK Release
      - name: Build apk release project (APK)
        run: ./gradlew assembleRelease --stacktrace

      # Noted For Output [main_project_module]/build/outputs/apk/release/
      - name: Upload APK Release
        uses: actions/upload-artifact@v3
        with:
          name: APK release generated
          path: app/build/outputs/apk/release/
